## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
# 設定 data_path
dir_data = './data/'

In [4]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [18]:
coln = app_train.shape[1]
row = app_train.shape[0]
print('column number: ', coln)
print('row number: ', row)

column number:  122
row number:  307511

#### 列出所有欄位

In [19]:
app_train.head(None)

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
20,100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
29,100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,456225,1,Cash loans,M,N,Y,0,225000.000,297000.0,19975.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307482,456226,0,Cash loans,F,Y,Y,0,225000.000,500566.5,34969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307483,456227,0,Cash loans,F,N,Y,0,99000.000,247275.0,16479.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
307484,456228,0,Cash loans,F,Y,N,0,540000.000,545040.0,35617.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307485,456229,0,Revolving loans,F,N,Y,1,270000.000,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307486,456230,0,Cash loans,F,Y,Y,1,292500.000,355536.0,18283.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307487,456231,0,Cash loans,M,N,Y,0,117000.000,1071909.0,31473.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
307488,456232,0,Cash loans,F,N,N,0,157500.000,135000.0,13351.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307489,456233,1,Cash loans,F,N,Y,0,225000.000,521280.0,23089.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
307490,456234,0,Cash loans,M,N,Y,0,81000.000,135000.0,9148.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307491,456235,0,Cash loans,M,Y,Y,2,90000.000,1078200.0,31522.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307492,456236,0,Cash loans,M,Y,Y,0,585000.000,1575000.0,43443.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307493,456237,0,Cash loans,F,N,Y,0,135000.000,946764.0,37678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307494,456238,0,Cash loans,M,Y,N,1,270000.000,479700.0,46858.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
307495,456239,0,Cash loans,M,Y,N,0,180000.000,808650.0,23773.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307496,456240,0,Revolving loans,F,N,N,0,360000.000,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307497,456241,0,Cash loans,F,Y,Y,0,180000.000,270126.0,12028.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
307498,456242,0,Cash loans,M,Y,Y,0,198000.000,1312110.0,52168.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307499,456243,0,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
307500,456244,0,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
307501,456245,0,Cash loans,F,N,Y,3,81000.000,269550.0,11871.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307502,456246,0,Cash loans,F,N,Y,1,94500.000,225000.0,10620.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307503,456247,0,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
307504,456248,0,Cash loans,F,N,Y,0,153000.000,331920.0,16096.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307505,456249,0,Cash loans,F,N,Y,0,112500.000,225000.0,22050.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
307506,456251,0,Cash loans,M,N,N,0,157500.000,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.000,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.000,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

#### 截取部分資料

In [22]:
app_train.iloc[555:666]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
555,100641,1,Cash loans,M,N,Y,0,112500.0,254700.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
556,100642,0,Cash loans,F,N,Y,0,157500.0,1350000.0,47056.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
557,100643,0,Cash loans,F,N,Y,0,90000.0,755190.0,29677.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
558,100644,0,Cash loans,F,Y,Y,2,76500.0,119925.0,13045.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
559,100645,0,Cash loans,M,Y,N,0,247500.0,900000.0,31887.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
560,100646,1,Cash loans,M,Y,Y,0,216000.0,640080.0,31261.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
561,100647,0,Revolving loans,F,N,Y,0,99000.0,247500.0,12375.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,7.0
562,100648,0,Cash loans,M,Y,N,0,67500.0,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
563,100649,1,Cash loans,F,N,N,2,180000.0,284400.0,13387.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
564,100650,1,Cash loans,M,N,N,0,135000.0,808650.0,31333.5,...,0,0,0,0,0.0,0.0,0.0,3.0,0.0,2.0
565,100651,0,Cash loans,F,Y,N,0,157500.0,634482.0,20596.5,...,0,0,0,0,0.0,0.0,0.0,0.0,3.0,3.0
566,100652,0,Cash loans,F,Y,Y,0,130500.0,995562.0,54684.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
567,100653,0,Cash loans,F,N,Y,1,247500.0,755856.0,38722.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
568,100654,0,Cash loans,F,N,Y,2,135000.0,427500.0,19939.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
569,100655,0,Revolving loans,M,N,Y,0,112500.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
570,100656,0,Cash loans,F,N,Y,0,54000.0,312768.0,13378.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
571,100657,0,Cash loans,F,N,N,0,135000.0,414792.0,16357.5,...,1,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
572,100658,0,Cash loans,F,N,N,1,189000.0,215640.0,11695.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
573,100659,0,Cash loans,F,N,Y,0,90000.0,603792.0,19606.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
574,100660,0,Revolving loans,M,N,Y,2,234000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
575,100661,0,Cash loans,M,Y,Y,0,202500.0,808650.0,31464.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
576,100662,0,Cash loans,F,N,Y,0,67500.0,152685.0,7924.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
577,100663,0,Cash loans,F,N,Y,0,112500.0,254700.0,17149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
578,100664,0,Cash loans,M,Y,Y,0,87750.0,314100.0,11767.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
579,100665,0,Revolving loans,F,N,Y,2,112500.0,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
580,100666,0,Cash loans,M,Y,Y,0,135000.0,422451.0,19822.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
581,100667,0,Cash loans,M,N,Y,0,45000.0,168102.0,16753.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
582,100668,0,Cash loans,F,N,N,1,144000.0,364896.0,16069.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
583,100669,0,Cash loans,M,Y,N,0,81000.0,670500.0,36504.0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0
584,100670,0,Cash loans,F,N,Y,0,112500.0,381528.0,14512.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636,100726,0,Cash loans,M,Y,N,0,202500.0,450000.0,17271.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
637,100727,0,Cash loans,F,Y,Y,0,112500.0,284400.0,10345.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
638,100728,0,Cash loans,F,N,N,0,112500.0,555273.0,16366.5,...,0,0,0,0,0.0,0.0,0.0,3.0,0.0,6.0
639,100730,0,Cash loans,F,N,Y,1,315000.0,1971072.0,62019.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
640,100731,0,Revolving loans,F,Y,Y,1,112500.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
641,100732,0,Cash loans,F,N,Y,0,225000.0,450000.0,22018.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
642,100733,0,Cash loans,F,N,N,0,157500.0,450000.0,20979.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
643,100734,0,Cash loans,F,Y,Y,1,157500.0,1218375.0,51750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
644,100735,0,Cash loans,F,Y,Y,1,292500.0,720000.0,25636.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
645,100736,0,Cash loans,M,Y,N,0,112500.0,1080000.0,34839.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,3.0
646,100737,0,Cash loans,F,N,Y,0,112500.0,247275.0,17208.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
647,100738,0,Revolving loans,F,N,Y,2,135000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
648,100739,0,Revolving loans,F,N,Y,2,216000.0,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
649,100741,0,Cash loans,M,Y,Y,0,90000.0,284400.0,19134.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
650,100742,0,Cash loans,F,N,Y,0,108000.0,390960.0,17352.0,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,0.0
651,100743,0,Cash loans,F,N,Y,0,38250.0,47970.0,5166.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
652,100746,0,Revolving loans,M,Y,Y,0,171000.0,495000.0,24750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
653,100748,0,Cash loans,F,Y,Y,1,103500.0,270000.0,14778.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
654,100749,0,Cash loans,F,N,N,0,171000.0,679500.0,19998.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
655,100750,0,Cash loans,F,N,Y,0,121500.0,472500.0,19993.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
656,100755,0,Cash loans,F,N,Y,0,90000.0,107820.0,7420.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
657,100756,0,Cash loans,F,N,Y,0,202500.0,247675.5,25506.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
658,100757,0,Cash loans,F,N,N,0,180000.0,675000.0,21906.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
659,100758,0,Cash loans,F,N,Y,1,157500.0,448056.0,17019.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
660,100759,0,Cash loans,M,Y,N,2,202500.0,938304.0,50121.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,1.0
661,100761,0,Cash loans,F,N,N,0,225000.0,225000.0,14778.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
662,100764,0,Revolving loans,M,Y,Y,0,135000.0,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
663,100766,0,Cash loans,M,Y,Y,2,126000.0,157050.0,9621.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
664,100767,0,Cash loans,M,N,Y,0,157500.0,808650.0,31464.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
665,100768,0,Cash loans,M,Y,N,0,112500.0,277969.5,10606.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子